name = "Skyrocket Team"
description = "Rocketry team from Goi√°s, Brazil"
keywords = "Engineering, Rockets"
image = "skyrocket.png"
theme = "dark"
primary_color = "#d81b60"
text_align = "center"
base_url = "http://skyrocketteam.github.io/"

[[sections]]
title = "Link"
description = ""
direction = "row"
item_style = "filled"
[[sections.items]]
title = "Rifa"
url = "https://rifa.digital/s/rifa-skyrocket-team-2023567650"
title = "Instagram"
url = "https://www.instagram.com/teamskyrocket/"
title = "Whatsapp"
url = "http://wa.me/556281712812"
title = "Linkedin"
url = "https://www.linkedin.com/company/teamskyrocket/?viewAsMember=true"
title = "Vakinha"
url = "https://www.vakinha.com.br/vaquinha/ajuda-para-desenvolvimento-de-um-foguete-universitario"
